version: '3.8'

services:
  rag-chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      GEMMA_MODEL: ${GEMMA_MODEL:-gemma:2b}
    volumes:
      - .:/app
      - faiss_data:/app/faiss_db
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  faiss_data:
